 'tryton/binutils/2.34' load complete.
 'tryton/compiler/gcc/7.4' load complete.
 'tryton/python3/3.5.6' load complete.

Loading tryton/python3/3.5.6
  Loading requirement: tryton/binutils/2.34 tryton/compiler/gcc/7.4
No handles with labels found to put in legend.
<stdin>:93: RuntimeWarning: invalid value encountered in true_divide
The plot is for alpha = 0
Traceback (most recent call last):
  File "<stdin>", line 104, in <module>
  File "/users/kdm/borhan/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
TypeError: savefig() takes 2 positional arguments but 3 were given
